Repository jenkinsci/claim-plugin, pull requests merged in 2023-01, with the labels that each got.

#196 Switch to latest 2.361 LTS version
  Jenkinsfile
Labels: dependencies

#195 dropClaim not visible for OpenID Connect Authentication
  src/main/java/hudson/plugins/claim/AbstractClaimBuildAction.java
Labels: bug

#198 Use user display names in mails and enhance anonymous user detection
  src/main/java/hudson/plugins/claim/AbstractClaimBuildAction.java
  src/main/java/hudson/plugins/claim/ClaimBuildAction.java
  src/main/java/hudson/plugins/claim/ClaimEmailer.java
  src/main/java/hudson/plugins/claim/ClaimPublisher.java
  src/main/java/hudson/plugins/claim/ClaimTestAction.java
  src/main/java/hudson/plugins/claim/ClaimTestDataPublisher.java
  src/main/java/hudson/plugins/claim/CommonMessagesProvider.java
  src/test/java/hudson/plugins/claim/ClaimEmailerTest.java
  src/test/java/hudson/plugins/claim/ClaimReportTest.java
  src/test/java/hudson/plugins/claim/ClaimTest.java
  src/test/java/hudson/plugins/claim/UserClaimsReportTest.java
Labels: enhancement

#200 JENKINS-70417: Add option to display email address near user full namen for in drop …
  src/main/java/hudson/plugins/claim/ClaimConfig.java
  src/main/java/hudson/plugins/claim/DescribableTestAction.java
  src/main/resources/hudson/plugins/claim/ClaimConfig/config.jelly
  src/main/resources/hudson/plugins/claim/ClaimConfig/config.properties
  src/main/webapp/help-emailDisplayedForAssigneesList.html
Labels: feature
